### ISSUE TITLE
Robot catkin path variable on base

### ISSUE THREAD

**Issue by danieldiamont** [UTNuclearRoboticsPublic/project-crunch#30] opened 2019-04-22 19:21 UTC
![image](https://user-images.githubusercontent.com/17392378/56520150-61b6ed00-6509-11e9-8406-2ebdd6e2d5c5.png)

**Comment by jsigee87** [comment] 2019-04-27 20:22
Duplicate of #44

**Closed as completed by jsigee87** 2019-04-27 20:22 UTC
Labels: bug
